# Generated by Django 4.2.1 on 2023-07-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
