# Generated by Django 3.2.20 on 2023-07-05 22:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vet.models.rendez_vous


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif_rendez_vous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateTimeField()),
                ('valeur', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rendez_vous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_prise', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_consultation', models.DateTimeField(default=django.utils.timezone.now)),
                ('duree', models.IntegerField(default=1, validators=[vet.models.rendez_vous.validate_positive_integer])),
                ('raison', models.CharField(max_length=700)),
                ('temps', models.IntegerField(default=0, validators=[vet.models.rendez_vous.validate_positive_integer])),
                ('prix', models.FloatField(validators=[vet.models.rendez_vous.validate_positive_float])),
                ('etat', models.IntegerField(default=0, validators=[vet.models.rendez_vous.validate_positive_integer])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globale.patient')),
            ],
        ),
    ]
