# Generated by Django 3.2.20 on 2023-07-05 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nourriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('prix_par_unite', models.FloatField()),
                ('unite', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_prise', models.DateTimeField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix', models.FloatField()),
                ('etat', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globale.client')),
            ],
        ),
        migrations.CreateModel(
            name='Validation_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifs_Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changement_tarif', models.DateField()),
                ('montant_journalier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_horaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globale.race')),
            ],
        ),
        migrations.CreateModel(
            name='Details_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence', models.IntegerField()),
                ('medicaments', models.BooleanField()),
                ('nourriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.nourriture')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globale.patient')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_interval_poids', models.IntegerField()),
                ('fin_interval_poids', models.IntegerField()),
                ('nourriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.nourriture')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globale.race')),
            ],
        ),
        migrations.CreateModel(
            name='Animal_accepte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_interval_age', models.IntegerField()),
                ('fin_interval_age', models.IntegerField()),
                ('debut_interval_validite', models.DateField()),
                ('fin_interval_validite', models.DateField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globale.race')),
            ],
        ),
    ]
