# Generated by Django 4.2.1 on 2023-06-07 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nourriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_journalier', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_prise', models.DateTimeField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix', models.FloatField()),
                ('etat', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.client')),
            ],
        ),
        migrations.CreateModel(
            name='Rendez_vous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_prise', models.DateTimeField()),
                ('date_consultation', models.DateTimeField()),
                ('raison', models.CharField(max_length=255)),
                ('temps', models.IntegerField()),
                ('prix', models.FloatField()),
                ('etat', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.poste')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.race'),
        ),
        migrations.AddField(
            model_name='patient',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.client'),
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=255)),
                ('identifiant', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('etat', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.client')),
                ('interlocuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Details_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence', models.IntegerField()),
                ('medicaments', models.BooleanField()),
                ('nourriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.nourriture')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.patient')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_interval_poids', models.IntegerField()),
                ('fin_interval_poids', models.IntegerField()),
                ('nourriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.nourriture')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.race')),
            ],
        ),
        migrations.CreateModel(
            name='Animal_accepte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_interval_age', models.IntegerField()),
                ('fin_interval_age', models.IntegerField()),
                ('debut_interval_validite', models.DateField()),
                ('fin_interval_validite', models.DateField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.race')),
            ],
        ),
    ]
