# Generated by Django 4.2.1 on 2023-06-07 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='nourriture',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='race',
        ),
        migrations.RemoveField(
            model_name='details_reservation',
            name='nourriture',
        ),
        migrations.RemoveField(
            model_name='details_reservation',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='details_reservation',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='client',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='interlocuteur',
        ),
        migrations.RemoveField(
            model_name='login',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='rendez_vous',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.DeleteModel(
            name='Animal_accepte',
        ),
        migrations.DeleteModel(
            name='Attribution',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Details_reservation',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Nourriture',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Poste',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='Rendez_vous',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
