# Generated by Django 4.2.1 on 2023-06-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='rendez_vous',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Poste',
        ),
        migrations.DeleteModel(
            name='Rendez_vous',
        ),
    ]
