# Generated by Django 4.2.1 on 2023-06-23 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0004_remove_login_personnel_remove_personnel_poste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.reservation')),
            ],
        ),
    ]
