# Generated by Django 4.2.1 on 2023-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0005_validation_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nom',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
